import React from 'react';
import Head from "next/head";
import boxes from '@/data/boxes';
import Sidebar from '@/sections/admin/Sidebar';
import Main from '@/sections/admin/Main';

const Admin1 = () => {
  const [currentBox, setCurrentBox] = React.useState(boxes[0]);

  return (
    <>
      <Head>
        <title>Admin Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={"flex admin-page py-16 px-5"}>
        {/* <Sidebar boxes={boxes} currentBox={currentBox} setCurrentBox={setCurrentBox} />
        {
          boxes.length > 0 && <Main box={currentBox} />
        } */}
      </div>
    </>
  );
};

export default Admin1;