import React from 'react';
import Heading from "../sections/claim/Heading";
import NFTCard from "../components/claim/NFTCard";
import CardsSection from "../sections/claim/CardsSection";
import {ModalContext} from "@/contexts/modal-context";
import Head from "next/head";
import LiveFeed from "@/components/LiveFeed";
import Image from "next/image";

const Claim = () => {
  const {showModal} = React.useContext(ModalContext)
  const [cards, setCards] = React.useState<{ name: string, box: string, image: string }[]>([])
  React.useEffect(() => {
    for (let i = 0; i < 4; i++) {
      setCards(prevState => [...prevState, {
        name: `NFT Name ${i}`,
        box: `Box Name ${i}`,
        image: '/images/002.jpg'
      }])
    }
  }, [])

  return (
    <>
      <Head>
        <title>Claim Prizes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="px-5 lg:px-32">
        <Heading/>
        <div className={"my-5"}>
          <p className={"font-bold font-space-mono text-[18px] my-5"}>TOKENS</p>
          <div className={"flex place-items-center gap-2"}>
            <Image width={16} height={16} className={"w-[16px] h-[16px]"} src="/images/solana.svg" alt=""/>
            <p className={"font-space-mono"}>1,000 SOL</p>
          </div>
          <div className={"flex place-items-center gap-2"}>
            <Image width={16} height={16} className={"w-[16px] h-[16px]"} src="/images/coin.png" alt=""/>
            <p className={"font-space-mono"}>1,000 ZEN</p>
          </div>
        </div>
        <CardsSection sectionName={'NFTs'}>
          {
            cards.map((card, index) => {
              return (
                <NFTCard key={index} name={card.name} box={card.box} image={card.image} handler={() => {
                  alert(`Claiming handler for ${card.name}`)
                  showModal(
                    <NFTCard key={`modal${index}`} image={card.image} name={card.name} claiming/>
                  )
                }}/>
              )
            })
          }
        </CardsSection>
        <CardsSection sectionName={'Other Prizes'}>
          {
            cards.map((card, index) => {
              return (
                <NFTCard key={index} name={card.name} box={card.box} image={card.image} handler={() => {
                  alert(`Claiming handler for ${card.name}`)
                  showModal(
                    <NFTCard key={`modal${index}`} image={card.image} name={card.name} claiming/>
                  )
                }}/>
              )
            })
          }
        </CardsSection>
      </div>
      <LiveFeed />
    </>
  );
};

export default Claim;