import { Banner } from '@/sections/lootboxes/Banner'
import { Boxes } from '@/sections/lootboxes/Boxes'
import { Prizes } from '@/sections/lootboxes/Prizes'
import Head from 'next/head'
import LiveFeed from "@/components/LiveFeed";
import React, { useState } from "react";
import useProgram from '@/hooks/useProgram';
import useFetchAllLootboxes from '@/hooks/useFetchAllLootboxes';

export default function Home() {
  const program = useProgram();
  const [reload, setReload] = useState({});
  const { lootboxes } = useFetchAllLootboxes(reload);
  return (
    <>
      <Head>
        <title>Lootbox</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="px-5 lg:px-32">
        <Banner/>
        <Prizes lootboxes={lootboxes}/>
        <Boxes lootboxes={lootboxes} setReload={setReload} />
        <LiveFeed />
      </div>
    </>
  )
}
