import { Banner } from '@/sections/lootboxes/Banner'
import { Boxes } from '@/sections/lootboxes/Boxes'
import { RecentlyWonPrizes } from '@/sections/lootboxes/RecentlyWonPrizes'
import Head from 'next/head'
import { useState } from "react";
import useFetchAllLootboxes from '@/hooks/useFetchAllLootboxes';
import useFetchEvents from '@/hooks/useFetchEvents';

export default function Home() {
  const [reload] = useState({});
  const { lootboxes } = useFetchAllLootboxes(reload);
  const { events } = useFetchEvents(reload);

  return (
    <>
      <Head>
        <title>Lootbox</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="px-5 lg:px-32">
        <Banner />
        <RecentlyWonPrizes events={events} />
        <Boxes lootboxes={lootboxes} />
      </div>
    </>
  )
}
