[features]
seeds = false
skip-lint = false
[programs.mainnet]
lootbox = "F8CacAyTqgYCnuLVLy8CVB3LGN2nqschYsVETxAMc1sk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "/home/work/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
